"""remove_telemedicine_tables

Revision ID: 067683c1dab3
Revises: eadec4bba3a0
Create Date: 2026-01-30 10:36:01.501715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '067683c1dab3'
down_revision = 'eadec4bba3a0'
branch_labels = None
depends_on = None


def _drop_fk_on_column_if_exists(conn, table_name, column_name='tele_appointment_id'):
    """Drop FK constraint on table that references the given column, if it exists."""
    insp = inspect(conn)
    if table_name not in insp.get_table_names():
        return
    for fk in insp.get_foreign_keys(table_name):
        constrained = fk.get('constrained_columns') or []
        if column_name in constrained:
            op.drop_constraint(fk['name'], table_name, type_='foreignkey')
            return


def _table_exists(conn, table_name):
    return table_name in inspect(conn).get_table_names()


def _drop_table_if_exists(conn, table_name):
    if _table_exists(conn, table_name):
        op.drop_table(table_name)


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables in order. telemed_sessions references tele_appointments,
    # and several tables reference telemed_sessions. Drop leaf tables first.

    # 1. Drop tele_prescriptions FKs to tele_appointments and telemed_sessions (if they exist)
    _drop_fk_on_column_if_exists(conn, 'tele_prescriptions', 'tele_appointment_id')
    _drop_fk_on_column_if_exists(conn, 'tele_prescriptions', 'session_id')

    # 2. Drop tables that reference telemed_sessions (so we can drop telemed_sessions)
    for t in (
        'telemed_notifications',
        'telemed_messages',
        'telemed_files',
        'telemed_consultation_notes',
        'telemed_vitals',
        'telemed_participants',
    ):
        _drop_table_if_exists(conn, t)

    # 3. Drop telemed_sessions (depends on tele_appointments)
    _drop_table_if_exists(conn, 'telemed_sessions')

    # 4. Drop video_sessions (depends on tele_appointments)
    _drop_table_if_exists(conn, 'video_sessions')

    # 5. Drop tele_appointments
    _drop_table_if_exists(conn, 'tele_appointments')
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ### (idempotent: only create if missing)
    if _table_exists(conn, 'tele_prescriptions') and _table_exists(conn, 'tele_appointments'):
        op.create_foreign_key('tele_prescriptions_tele_appointment_id_fkey', 'tele_prescriptions', 'tele_appointments', ['tele_appointment_id'], ['id'])
    if not _table_exists(conn, 'video_sessions'):
        op.create_table('video_sessions',
            sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('hospital_id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('tele_appointment_id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
            sa.Column('provider', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
            sa.Column('doctor_join_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
            sa.Column('patient_join_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
            sa.Column('session_start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
            sa.Column('session_end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
            sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
            sa.Column('room_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
            sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('doctor_joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
            sa.Column('patient_joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
            sa.Column('doctor_left_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
            sa.Column('patient_left_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
            sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
            sa.Column('ended_by', sa.UUID(), autoincrement=False, nullable=True),
            sa.Column('end_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
            sa.Column('provider_data', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
            sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
            sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['ended_by'], ['users.id'], name='video_sessions_ended_by_fkey'),
            sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name='video_sessions_hospital_id_fkey'),
            sa.ForeignKeyConstraint(['tele_appointment_id'], ['tele_appointments.id'], name='video_sessions_tele_appointment_id_fkey'),
            sa.PrimaryKeyConstraint('id', name='video_sessions_pkey')
        )
        op.create_index('ix_video_sessions_tele_appointment_id', 'video_sessions', ['tele_appointment_id'], unique=False)
        op.create_index('ix_video_sessions_status', 'video_sessions', ['status'], unique=False)
        op.create_index('ix_video_sessions_session_id', 'video_sessions', ['session_id'], unique=True)
        op.create_index('ix_video_sessions_hospital_id', 'video_sessions', ['hospital_id'], unique=False)
    if not _table_exists(conn, 'tele_appointments'):
        op.create_table('tele_appointments',
            sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('hospital_id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
            sa.Column('scheduled_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
            sa.Column('start_time', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
            sa.Column('end_time', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
            sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
            sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('session_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
            sa.Column('session_ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
            sa.Column('actual_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
            sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
            sa.Column('cancellation_reason', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('cancelled_by', sa.UUID(), autoincrement=False, nullable=True),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
            sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
            sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='tele_appointments_appointment_id_fkey'),
            sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], name='tele_appointments_cancelled_by_fkey'),
            sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='tele_appointments_doctor_id_fkey'),
            sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name='tele_appointments_hospital_id_fkey'),
            sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name='tele_appointments_patient_id_fkey'),
            sa.PrimaryKeyConstraint('id', name='tele_appointments_pkey')
        )
        op.create_index('ix_tele_appointments_status', 'tele_appointments', ['status'], unique=False)
        op.create_index('ix_tele_appointments_scheduled_date', 'tele_appointments', ['scheduled_date'], unique=False)
        op.create_index('ix_tele_appointments_patient_id', 'tele_appointments', ['patient_id'], unique=False)
        op.create_index('ix_tele_appointments_hospital_id', 'tele_appointments', ['hospital_id'], unique=False)
        op.create_index('ix_tele_appointments_doctor_id', 'tele_appointments', ['doctor_id'], unique=False)
        op.create_index('ix_tele_appointments_appointment_id', 'tele_appointments', ['appointment_id'], unique=True)
    # ### end Alembic commands ###