"""add_equipment_qc_tables

Revision ID: 19063f6ca87c
Revises: lab_result_entry_003
Create Date: 2026-01-29 12:01:32.069104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '19063f6ca87c'
down_revision = '129cde14c188'  # 129cde14c188 -> 19063f6ca87c -> 7b5d54dd0674 -> make_doctor_id_nullable
branch_labels = None
depends_on = None


def _table_exists(conn, name):
    return name in inspect(conn).get_table_names()


def _column_exists(conn, table, column):
    if table not in inspect(conn).get_table_names():
        return False
    return column in [c["name"] for c in inspect(conn).get_columns(table)]


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists(conn, 'lab_equipment'):
        op.create_table('lab_equipment',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('hospital_id', sa.UUID(), nullable=False),
            sa.Column('equipment_code', sa.String(length=50), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('category', sa.String(length=20), nullable=False),
            sa.Column('manufacturer', sa.String(length=100), nullable=True),
            sa.Column('model', sa.String(length=100), nullable=True),
            sa.Column('serial_number', sa.String(length=100), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('installation_date', sa.DateTime(timezone=True), nullable=True),
            sa.Column('last_calibrated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('next_calibration_due_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('location', sa.String(length=100), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('specifications', sa.JSON(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_lab_equipment_equipment_code'), 'lab_equipment', ['equipment_code'], unique=False)
        op.create_index(op.f('ix_lab_equipment_hospital_id'), 'lab_equipment', ['hospital_id'], unique=False)
    if not _table_exists(conn, 'equipment_maintenance_logs'):
        op.create_table('equipment_maintenance_logs',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('equipment_id', sa.UUID(), nullable=False),
            sa.Column('type', sa.String(length=20), nullable=False),
            sa.Column('performed_by', sa.UUID(), nullable=False),
            sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('remarks', sa.Text(), nullable=True),
            sa.Column('attachment_ref', sa.String(length=500), nullable=True),
            sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
            sa.Column('service_provider', sa.String(length=200), nullable=True),
            sa.Column('service_ticket_no', sa.String(length=100), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['equipment_id'], ['lab_equipment.id'], ),
            sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_equipment_maintenance_logs_equipment_id'), 'equipment_maintenance_logs', ['equipment_id'], unique=False)
    if not _table_exists(conn, 'qc_rules'):
        op.create_table('qc_rules',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('hospital_id', sa.UUID(), nullable=False),
            sa.Column('section', sa.String(length=20), nullable=False),
            sa.Column('test_code', sa.String(length=50), nullable=True),
            sa.Column('frequency', sa.String(length=20), nullable=False),
            sa.Column('validity_hours', sa.Integer(), nullable=False),
            sa.Column('parameter_name', sa.String(length=100), nullable=False),
            sa.Column('min_value', sa.DECIMAL(precision=10, scale=3), nullable=True),
            sa.Column('max_value', sa.DECIMAL(precision=10, scale=3), nullable=True),
            sa.Column('target_value', sa.DECIMAL(precision=10, scale=3), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('created_by', sa.UUID(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
            sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_qc_rules_hospital_id'), 'qc_rules', ['hospital_id'], unique=False)
        op.create_index(op.f('ix_qc_rules_section'), 'qc_rules', ['section'], unique=False)
        op.create_index(op.f('ix_qc_rules_test_code'), 'qc_rules', ['test_code'], unique=False)
    if not _table_exists(conn, 'qc_runs'):
        op.create_table('qc_runs',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('hospital_id', sa.UUID(), nullable=False),
            sa.Column('equipment_id', sa.UUID(), nullable=False),
            sa.Column('qc_rule_id', sa.UUID(), nullable=False),
            sa.Column('section', sa.String(length=20), nullable=False),
            sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('run_by', sa.UUID(), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('values', sa.JSON(), nullable=True),
            sa.Column('batch_number', sa.String(length=100), nullable=True),
            sa.Column('lot_number', sa.String(length=100), nullable=True),
            sa.Column('remarks', sa.Text(), nullable=True),
            sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['equipment_id'], ['lab_equipment.id'], ),
            sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
            sa.ForeignKeyConstraint(['qc_rule_id'], ['qc_rules.id'], ),
            sa.ForeignKeyConstraint(['run_by'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_qc_runs_equipment_id'), 'qc_runs', ['equipment_id'], unique=False)
        op.create_index(op.f('ix_qc_runs_hospital_id'), 'qc_runs', ['hospital_id'], unique=False)
        op.create_index(op.f('ix_qc_runs_qc_rule_id'), 'qc_runs', ['qc_rule_id'], unique=False)
        op.create_index(op.f('ix_qc_runs_run_at'), 'qc_runs', ['run_at'], unique=False)
        op.create_index(op.f('ix_qc_runs_section'), 'qc_runs', ['section'], unique=False)
    # Alterations: skip if already applied (idempotent for stamp sync)
    if _table_exists(conn, 'lab_order_items') and not _column_exists(conn, 'lab_order_items', 'is_active'):
        op.add_column('lab_order_items', sa.Column('is_active', sa.Boolean(), nullable=False))
    if _table_exists(conn, 'lab_orders') and not _column_exists(conn, 'lab_orders', 'is_active'):
        op.add_column('lab_orders', sa.Column('is_active', sa.Boolean(), nullable=False))
    if _table_exists(conn, 'lab_orders'):
        op.execute('ALTER TABLE lab_orders DROP CONSTRAINT IF EXISTS lab_orders_lab_order_no_key')
        op.execute('DROP INDEX IF EXISTS ix_lab_orders_lab_order_no')
        op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_lab_orders_lab_order_no ON lab_orders (lab_order_no)')
    if _table_exists(conn, 'lab_reports'):
        op.execute('ALTER TABLE lab_reports DROP CONSTRAINT IF EXISTS lab_reports_report_number_key')
        op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_lab_reports_report_number ON lab_reports (report_number)')
    if _table_exists(conn, 'lab_samples') and not _column_exists(conn, 'lab_samples', 'is_active'):
        op.add_column('lab_samples', sa.Column('is_active', sa.Boolean(), nullable=False))
    if _table_exists(conn, 'lab_samples'):
        op.execute('ALTER TABLE lab_samples DROP CONSTRAINT IF EXISTS lab_samples_barcode_value_key')
        op.execute('ALTER TABLE lab_samples DROP CONSTRAINT IF EXISTS lab_samples_sample_no_key')
        op.execute('DROP INDEX IF EXISTS ix_lab_samples_barcode_value')
        op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_lab_samples_barcode_value ON lab_samples (barcode_value)')
        op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_lab_samples_sample_no ON lab_samples (sample_no)')
    if _table_exists(conn, 'lab_tests'):
        op.execute('DROP INDEX IF EXISTS uq_test_code_per_hospital')
    if _table_exists(conn, 'result_values') and not _column_exists(conn, 'result_values', 'is_active'):
        op.add_column('result_values', sa.Column('is_active', sa.Boolean(), nullable=False))
    if _table_exists(conn, 'sample_order_items'):
        if not _column_exists(conn, 'sample_order_items', 'updated_at'):
            op.add_column('sample_order_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        if not _column_exists(conn, 'sample_order_items', 'is_active'):
            op.add_column('sample_order_items', sa.Column('is_active', sa.Boolean(), nullable=False))
        op.execute('DROP INDEX IF EXISTS uq_sample_order_item_mapping')
    if _table_exists(conn, 'test_results') and not _column_exists(conn, 'test_results', 'is_active'):
        op.add_column('test_results', sa.Column('is_active', sa.Boolean(), nullable=False))
    if _table_exists(conn, 'test_results'):
        op.execute('DROP INDEX IF EXISTS uq_test_result_per_order_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ### (idempotent: only alter/drop if table exists)
    if _table_exists(conn, 'test_results'):
        op.execute('DROP INDEX IF EXISTS uq_test_result_per_order_item')
        op.create_index('uq_test_result_per_order_item', 'test_results', ['lab_order_item_id'], unique=True)
        if _column_exists(conn, 'test_results', 'is_active'):
            op.drop_column('test_results', 'is_active')
    if _table_exists(conn, 'sample_order_items'):
        op.execute('DROP INDEX IF EXISTS uq_sample_order_item_mapping')
        op.create_index('uq_sample_order_item_mapping', 'sample_order_items', ['sample_id', 'lab_order_item_id'], unique=True)
        if _column_exists(conn, 'sample_order_items', 'is_active'):
            op.drop_column('sample_order_items', 'is_active')
        if _column_exists(conn, 'sample_order_items', 'updated_at'):
            op.drop_column('sample_order_items', 'updated_at')
    if _table_exists(conn, 'result_values') and _column_exists(conn, 'result_values', 'is_active'):
        op.drop_column('result_values', 'is_active')
    if _table_exists(conn, 'lab_tests'):
        op.execute('DROP INDEX IF EXISTS uq_test_code_per_hospital')
        op.create_index('uq_test_code_per_hospital', 'lab_tests', ['hospital_id', 'test_code'], unique=True)
    if _table_exists(conn, 'lab_samples'):
        op.drop_index(op.f('ix_lab_samples_sample_no'), table_name='lab_samples')
        op.drop_index(op.f('ix_lab_samples_barcode_value'), table_name='lab_samples')
        op.create_index('ix_lab_samples_barcode_value', 'lab_samples', ['barcode_value'], unique=False)
        op.create_unique_constraint('lab_samples_sample_no_key', 'lab_samples', ['sample_no'])
        op.create_unique_constraint('lab_samples_barcode_value_key', 'lab_samples', ['barcode_value'])
        if _column_exists(conn, 'lab_samples', 'is_active'):
            op.drop_column('lab_samples', 'is_active')
    if _table_exists(conn, 'lab_reports'):
        op.drop_index(op.f('ix_lab_reports_report_number'), table_name='lab_reports')
        op.create_unique_constraint('lab_reports_report_number_key', 'lab_reports', ['report_number'])
    if _table_exists(conn, 'lab_orders'):
        op.drop_index(op.f('ix_lab_orders_lab_order_no'), table_name='lab_orders')
        op.create_index('ix_lab_orders_lab_order_no', 'lab_orders', ['lab_order_no'], unique=False)
        op.create_unique_constraint('lab_orders_lab_order_no_key', 'lab_orders', ['lab_order_no'])
        if _column_exists(conn, 'lab_orders', 'is_active'):
            op.drop_column('lab_orders', 'is_active')
    if _table_exists(conn, 'lab_order_items') and _column_exists(conn, 'lab_order_items', 'is_active'):
        op.drop_column('lab_order_items', 'is_active')
    if _table_exists(conn, 'qc_runs'):
        op.drop_index(op.f('ix_qc_runs_section'), table_name='qc_runs')
        op.drop_index(op.f('ix_qc_runs_run_at'), table_name='qc_runs')
        op.drop_index(op.f('ix_qc_runs_qc_rule_id'), table_name='qc_runs')
        op.drop_index(op.f('ix_qc_runs_hospital_id'), table_name='qc_runs')
        op.drop_index(op.f('ix_qc_runs_equipment_id'), table_name='qc_runs')
        op.drop_table('qc_runs')
    if _table_exists(conn, 'qc_rules'):
        op.drop_index(op.f('ix_qc_rules_test_code'), table_name='qc_rules')
        op.drop_index(op.f('ix_qc_rules_section'), table_name='qc_rules')
        op.drop_index(op.f('ix_qc_rules_hospital_id'), table_name='qc_rules')
        op.drop_table('qc_rules')
    if _table_exists(conn, 'equipment_maintenance_logs'):
        op.drop_index(op.f('ix_equipment_maintenance_logs_equipment_id'), table_name='equipment_maintenance_logs')
        op.drop_table('equipment_maintenance_logs')
    if _table_exists(conn, 'lab_equipment'):
        op.drop_index(op.f('ix_lab_equipment_hospital_id'), table_name='lab_equipment')
        op.drop_index(op.f('ix_lab_equipment_equipment_code'), table_name='lab_equipment')
        op.drop_table('lab_equipment')
    # ### end Alembic commands ###