"""add_prescription_tables

Revision ID: eadec4bba3a0
Revises: add_telemedicine_tables
Create Date: 2026-01-30 10:30:58.318879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'eadec4bba3a0'
down_revision = 'add_telemedicine_tables'
branch_labels = None
depends_on = None


def _table_exists(conn, name):
    return name in inspect(conn).get_table_names()


def _column_exists(conn, table_name, column_name):
    cols = [c["name"] for c in inspect(conn).get_columns(table_name)]
    return column_name in cols


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists(conn, 'tele_prescriptions'):
        op.create_table('tele_prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tele_appointment_id', sa.UUID(), nullable=True),
    sa.Column('prescription_no', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by', sa.UUID(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tele_appointment_id'], ['tele_appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tele_prescriptions_doctor_id'), 'tele_prescriptions', ['doctor_id'], unique=False)
        op.create_index(op.f('ix_tele_prescriptions_hospital_id'), 'tele_prescriptions', ['hospital_id'], unique=False)
        op.create_index(op.f('ix_tele_prescriptions_patient_id'), 'tele_prescriptions', ['patient_id'], unique=False)
        op.create_index(op.f('ix_tele_prescriptions_prescription_no'), 'tele_prescriptions', ['prescription_no'], unique=True)
        op.create_index(op.f('ix_tele_prescriptions_status'), 'tele_prescriptions', ['status'], unique=False)
        op.create_index(op.f('ix_tele_prescriptions_tele_appointment_id'), 'tele_prescriptions', ['tele_appointment_id'], unique=True)
    if not _table_exists(conn, 'prescription_integrations'):
        op.create_table('prescription_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('integration_type', sa.String(length=20), nullable=False),
    sa.Column('target_module', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['tele_prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_prescription_integrations_hospital_id'), 'prescription_integrations', ['hospital_id'], unique=False)
        op.create_index(op.f('ix_prescription_integrations_integration_type'), 'prescription_integrations', ['integration_type'], unique=False)
        op.create_index(op.f('ix_prescription_integrations_prescription_id'), 'prescription_integrations', ['prescription_id'], unique=False)
        op.create_index(op.f('ix_prescription_integrations_status'), 'prescription_integrations', ['status'], unique=False)
    if not _table_exists(conn, 'prescription_lab_orders'):
        lab_orders_cols = [
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('prescription_id', sa.UUID(), nullable=False),
            sa.Column('lab_test_id', sa.UUID(), nullable=True),
            sa.Column('test_name', sa.String(length=200), nullable=False),
            sa.Column('test_code', sa.String(length=50), nullable=True),
            sa.Column('test_category', sa.String(length=100), nullable=True),
            sa.Column('clinical_notes', sa.Text(), nullable=True),
            sa.Column('urgency', sa.String(length=20), nullable=False),
            sa.Column('sent_to_lab', sa.Boolean(), nullable=False),
            sa.Column('lab_order_id', sa.UUID(), nullable=True),
            sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('hospital_id', sa.UUID(), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
            sa.ForeignKeyConstraint(['prescription_id'], ['tele_prescriptions.id'], ),
            sa.PrimaryKeyConstraint('id'),
        ]
        if _table_exists(conn, 'lab_tests'):
            lab_orders_cols.insert(-1, sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], ))
        op.create_table('prescription_lab_orders', *lab_orders_cols)
        op.create_index(op.f('ix_prescription_lab_orders_hospital_id'), 'prescription_lab_orders', ['hospital_id'], unique=False)
        op.create_index(op.f('ix_prescription_lab_orders_prescription_id'), 'prescription_lab_orders', ['prescription_id'], unique=False)
    if not _table_exists(conn, 'prescription_medicines'):
        # Use pharmacy_medicines (this codebase) not medicines; skip medicine_id FK if pharmacy_medicines doesn't exist yet
        cols = [
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('prescription_id', sa.UUID(), nullable=False),
            sa.Column('medicine_id', sa.UUID(), nullable=True),
            sa.Column('medicine_name', sa.String(length=200), nullable=False),
            sa.Column('medicine_strength', sa.String(length=50), nullable=True),
            sa.Column('medicine_form', sa.String(length=50), nullable=True),
            sa.Column('dose', sa.String(length=50), nullable=False),
            sa.Column('frequency', sa.String(length=50), nullable=False),
            sa.Column('duration_days', sa.Integer(), nullable=False),
            sa.Column('instructions', sa.Text(), nullable=True),
            sa.Column('quantity', sa.Integer(), nullable=True),
            sa.Column('quantity_unit', sa.String(length=20), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('hospital_id', sa.UUID(), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
            sa.ForeignKeyConstraint(['prescription_id'], ['tele_prescriptions.id'], ),
            sa.PrimaryKeyConstraint('id'),
        ]
        if _table_exists(conn, 'pharmacy_medicines'):
            cols.insert(-1, sa.ForeignKeyConstraint(['medicine_id'], ['pharmacy_medicines.id'], ))
        op.create_table('prescription_medicines', *cols)
        op.create_index(op.f('ix_prescription_medicines_hospital_id'), 'prescription_medicines', ['hospital_id'], unique=False)
        op.create_index(op.f('ix_prescription_medicines_prescription_id'), 'prescription_medicines', ['prescription_id'], unique=False)
    if not _table_exists(conn, 'prescription_pdfs'):
        op.create_table('prescription_pdfs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('template_version', sa.String(length=20), nullable=True),
    sa.Column('access_token', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['tele_prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
        )
        op.create_index(op.f('ix_prescription_pdfs_hospital_id'), 'prescription_pdfs', ['hospital_id'], unique=False)
        op.create_index(op.f('ix_prescription_pdfs_prescription_id'), 'prescription_pdfs', ['prescription_id'], unique=False)
    # Add columns only if they don't exist (idempotent)
    if _table_exists(conn, 'chain_of_custody'):
        if not _column_exists(conn, 'chain_of_custody', 'updated_at'):
            op.add_column('chain_of_custody', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        if not _column_exists(conn, 'chain_of_custody', 'is_active'):
            op.add_column('chain_of_custody', sa.Column('is_active', sa.Boolean(), nullable=False))
    if _table_exists(conn, 'compliance_exports'):
        if not _column_exists(conn, 'compliance_exports', 'created_at'):
            op.add_column('compliance_exports', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        if not _column_exists(conn, 'compliance_exports', 'updated_at'):
            op.add_column('compliance_exports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        if not _column_exists(conn, 'compliance_exports', 'is_active'):
            op.add_column('compliance_exports', sa.Column('is_active', sa.Boolean(), nullable=False))
    if _table_exists(conn, 'lab_audit_logs'):
        if not _column_exists(conn, 'lab_audit_logs', 'updated_at'):
            op.add_column('lab_audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        if not _column_exists(conn, 'lab_audit_logs', 'is_active'):
            op.add_column('lab_audit_logs', sa.Column('is_active', sa.Boolean(), nullable=False))
    # Note: publish_status, published_at, published_by, unpublished_at, unpublished_by columns
    # and their foreign keys were already added in migration 129cde14c188_add_report_sharing_notification_tables
    if _table_exists(conn, 'tele_appointments') and not _column_exists(conn, 'tele_appointments', 'is_active'):
        op.add_column('tele_appointments', sa.Column('is_active', sa.Boolean(), nullable=False))
    if _table_exists(conn, 'tele_appointments'):
        for stmt_name, stmt in [
            ('drop_uc', lambda: op.drop_constraint('tele_appointments_appointment_id_key', 'tele_appointments', type_='unique')),
            ('drop_idx', lambda: op.drop_index('ix_tele_appointments_appointment_id', table_name='tele_appointments')),
            ('create_idx', lambda: op.create_index(op.f('ix_tele_appointments_appointment_id'), 'tele_appointments', ['appointment_id'], unique=True)),
        ]:
            conn.execute(sa.text("SAVEPOINT sp_ta"))
            try:
                stmt()
            except Exception:
                conn.execute(sa.text("ROLLBACK TO SAVEPOINT sp_ta"))
            else:
                conn.execute(sa.text("RELEASE SAVEPOINT sp_ta"))
    if _table_exists(conn, 'video_sessions') and not _column_exists(conn, 'video_sessions', 'is_active'):
        op.add_column('video_sessions', sa.Column('is_active', sa.Boolean(), nullable=False))
    if _table_exists(conn, 'video_sessions'):
        for stmt_name, stmt in [
            ('drop_uc', lambda: op.drop_constraint('video_sessions_session_id_key', 'video_sessions', type_='unique')),
            ('drop_idx', lambda: op.drop_index('ix_video_sessions_session_id', table_name='video_sessions')),
            ('create_idx', lambda: op.create_index(op.f('ix_video_sessions_session_id'), 'video_sessions', ['session_id'], unique=True)),
        ]:
            conn.execute(sa.text("SAVEPOINT sp_vs"))
            try:
                stmt()
            except Exception:
                conn.execute(sa.text("ROLLBACK TO SAVEPOINT sp_vs"))
            else:
                conn.execute(sa.text("RELEASE SAVEPOINT sp_vs"))
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ### (idempotent: only drop if table exists)
    if _table_exists(conn, 'video_sessions'):
        op.drop_index(op.f('ix_video_sessions_session_id'), table_name='video_sessions')
        op.create_index('ix_video_sessions_session_id', 'video_sessions', ['session_id'], unique=False)
        op.create_unique_constraint('video_sessions_session_id_key', 'video_sessions', ['session_id'])
        if _column_exists(conn, 'video_sessions', 'is_active'):
            op.drop_column('video_sessions', 'is_active')
    if _table_exists(conn, 'tele_appointments'):
        op.drop_index(op.f('ix_tele_appointments_appointment_id'), table_name='tele_appointments')
        op.create_index('ix_tele_appointments_appointment_id', 'tele_appointments', ['appointment_id'], unique=False)
        op.create_unique_constraint('tele_appointments_appointment_id_key', 'tele_appointments', ['appointment_id'])
        if _column_exists(conn, 'tele_appointments', 'is_active'):
            op.drop_column('tele_appointments', 'is_active')
    # Note: publish_status, published_at, published_by, unpublished_at, unpublished_by columns
    # and their foreign keys were added in migration 129cde14c188_add_report_sharing_notification_tables
    # so they should be dropped in that migration's downgrade, not here
    if _table_exists(conn, 'lab_audit_logs'):
        if _column_exists(conn, 'lab_audit_logs', 'is_active'):
            op.drop_column('lab_audit_logs', 'is_active')
        if _column_exists(conn, 'lab_audit_logs', 'updated_at'):
            op.drop_column('lab_audit_logs', 'updated_at')
    if _table_exists(conn, 'compliance_exports'):
        if _column_exists(conn, 'compliance_exports', 'is_active'):
            op.drop_column('compliance_exports', 'is_active')
        if _column_exists(conn, 'compliance_exports', 'updated_at'):
            op.drop_column('compliance_exports', 'updated_at')
        if _column_exists(conn, 'compliance_exports', 'created_at'):
            op.drop_column('compliance_exports', 'created_at')
    if _table_exists(conn, 'chain_of_custody'):
        if _column_exists(conn, 'chain_of_custody', 'is_active'):
            op.drop_column('chain_of_custody', 'is_active')
        if _column_exists(conn, 'chain_of_custody', 'updated_at'):
            op.drop_column('chain_of_custody', 'updated_at')
    if _table_exists(conn, 'prescription_pdfs'):
        op.drop_index(op.f('ix_prescription_pdfs_prescription_id'), table_name='prescription_pdfs')
        op.drop_index(op.f('ix_prescription_pdfs_hospital_id'), table_name='prescription_pdfs')
        op.drop_table('prescription_pdfs')
    if _table_exists(conn, 'prescription_medicines'):
        op.drop_index(op.f('ix_prescription_medicines_prescription_id'), table_name='prescription_medicines')
        op.drop_index(op.f('ix_prescription_medicines_hospital_id'), table_name='prescription_medicines')
        op.drop_table('prescription_medicines')
    if _table_exists(conn, 'prescription_lab_orders'):
        op.drop_index(op.f('ix_prescription_lab_orders_prescription_id'), table_name='prescription_lab_orders')
        op.drop_index(op.f('ix_prescription_lab_orders_hospital_id'), table_name='prescription_lab_orders')
        op.drop_table('prescription_lab_orders')
    if _table_exists(conn, 'prescription_integrations'):
        op.drop_index(op.f('ix_prescription_integrations_status'), table_name='prescription_integrations')
        op.drop_index(op.f('ix_prescription_integrations_prescription_id'), table_name='prescription_integrations')
        op.drop_index(op.f('ix_prescription_integrations_integration_type'), table_name='prescription_integrations')
        op.drop_index(op.f('ix_prescription_integrations_hospital_id'), table_name='prescription_integrations')
        op.drop_table('prescription_integrations')
    if _table_exists(conn, 'tele_prescriptions'):
        op.drop_index(op.f('ix_tele_prescriptions_tele_appointment_id'), table_name='tele_prescriptions')
        op.drop_index(op.f('ix_tele_prescriptions_status'), table_name='tele_prescriptions')
        op.drop_index(op.f('ix_tele_prescriptions_prescription_no'), table_name='tele_prescriptions')
        op.drop_index(op.f('ix_tele_prescriptions_patient_id'), table_name='tele_prescriptions')
        op.drop_index(op.f('ix_tele_prescriptions_hospital_id'), table_name='tele_prescriptions')
        op.drop_index(op.f('ix_tele_prescriptions_doctor_id'), table_name='tele_prescriptions')
        op.drop_table('tele_prescriptions')
    # ### end Alembic commands ###